"""GitHub integration — create repos and push generated artefacts."""

from __future__ import annotations

import os
from typing import Dict, List, Optional

from github import Auth, Github


def _get_client() -> Github:
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set.")
    return Github(auth=Auth.Token(token))


def get_authenticated_username() -> str:
    """Return the GitHub username for the current token."""
    g = _get_client()
    return g.get_user().login


def check_existing_repos(paper_title: str) -> List[Dict[str, str]]:
    """Check if the authenticated user already has repos matching the paper.

    Searches repo names and descriptions for keyword matches.

    Returns:
        List of dicts with 'name', 'url', and 'description' for matching repos.
    """
    try:
        g = _get_client()
        user = g.get_user()

        # Build keyword set from the paper title
        stop_words = {
            "a", "an", "the", "of", "for", "with", "and", "in", "on", "to",
            "is", "are", "by", "from", "via", "using", "as", "its", "that",
        }
        keywords = set()
        for w in paper_title.lower().split():
            cleaned = "".join(c for c in w if c.isalnum())
            if cleaned and len(cleaned) > 2 and cleaned not in stop_words:
                keywords.add(cleaned)

        if not keywords:
            return []

        matches = []
        for repo in user.get_repos(type="owner"):
            searchable = (
                (repo.name or "").lower().replace("-", " ").replace("_", " ")
                + " "
                + (repo.description or "").lower()
            )
            matched_kw = sum(1 for kw in keywords if kw in searchable)
            # Consider it a match if ≥40% of title keywords are found
            if matched_kw >= max(2, int(len(keywords) * 0.4)):
                matches.append({
                    "name": repo.name,
                    "url": repo.html_url,
                    "description": repo.description or "",
                })

        return matches
    except Exception:
        return []


def push_to_github(
    repo_name: str,
    files: Dict[str, str],
    description: str = "ML paper implementation generated by Paper2Code",
    private: bool = False,
) -> str:
    """Create a new GitHub repo and push files to it.

    Args:
        repo_name: Name for the new repository.
        files: Mapping of file paths (e.g. "src/main.py") to their content.
        description: Repo description.
        private: Whether the repo should be private.

    Returns:
        The HTML URL of the created repository.
    """
    g = _get_client()
    user = g.get_user()

    # Create repo (will raise if name is taken)
    repo = user.create_repo(
        name=repo_name,
        description=description,
        private=private,
        auto_init=True,  # creates an initial commit so we can push files
    )

    # Commit all files in a single commit
    # We use the Git Data API so we can commit many files at once
    # Get the default branch ref
    default_branch = repo.default_branch
    ref = repo.get_git_ref(f"heads/{default_branch}")
    base_tree = repo.get_git_tree(ref.object.sha)

    # Build tree entries
    tree_elements = []
    from github import InputGitTreeElement

    for path, content in files.items():
        tree_elements.append(
            InputGitTreeElement(
                path=path,
                mode="100644",
                type="blob",
                content=content,
            )
        )

    new_tree = repo.create_git_tree(tree_elements, base_tree)
    parent_commit = repo.get_git_commit(ref.object.sha)
    new_commit = repo.create_git_commit(
        message="🚀 Initial implementation — generated by Paper2Code",
        tree=new_tree,
        parents=[parent_commit],
    )
    ref.edit(sha=new_commit.sha)

    return repo.html_url
