"""Curated catalog of ~50 essential ML/AI papers for MS students."""

from __future__ import annotations

from typing import Dict, List, Optional

# Each paper entry
PAPERS = [
    # ═══════════════════════════════════════════════════════════════════════
    # FOUNDATIONS
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "attention-is-all-you-need",
        "title": "Attention Is All You Need",
        "authors": "Vaswani et al.",
        "year": 2017,
        "arxiv_url": "https://arxiv.org/abs/1706.03762",
        "category": "Foundations",
        "description": "Introduces the Transformer architecture, replacing recurrence with self-attention for sequence-to-sequence tasks.",
        "suggested_repo_name": "transformer-from-scratch",
    },
    {
        "id": "bert",
        "title": "BERT: Pre-training of Deep Bidirectional Transformers",
        "authors": "Devlin et al.",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1810.04805",
        "category": "Foundations",
        "description": "Bidirectional pre-training via masked language modeling and next sentence prediction.",
        "suggested_repo_name": "bert-implementation",
    },
    {
        "id": "gpt2",
        "title": "Language Models are Unsupervised Multitask Learners (GPT-2)",
        "authors": "Radford et al.",
        "year": 2019,
        "arxiv_url": "https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf",
        "category": "Foundations",
        "description": "Demonstrates that large language models can perform downstream tasks zero-shot.",
        "suggested_repo_name": "gpt2-implementation",
    },
    {
        "id": "resnet",
        "title": "Deep Residual Learning for Image Recognition",
        "authors": "He et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1512.03385",
        "category": "Foundations",
        "description": "Introduces skip connections enabling training of very deep networks (100+ layers).",
        "suggested_repo_name": "resnet-implementation",
    },
    {
        "id": "batch-norm",
        "title": "Batch Normalization: Accelerating Deep Network Training",
        "authors": "Ioffe & Szegedy",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1502.03167",
        "category": "Foundations",
        "description": "Normalizes activations within mini-batches to stabilize and speed up training.",
        "suggested_repo_name": "batch-norm-study",
    },
    {
        "id": "dropout",
        "title": "Dropout: A Simple Way to Prevent Neural Networks from Overfitting",
        "authors": "Srivastava et al.",
        "year": 2014,
        "arxiv_url": "https://jmlr.org/papers/v15/srivastava14a.html",
        "category": "Foundations",
        "description": "Randomly drops units during training as a regularization technique.",
        "suggested_repo_name": "dropout-regularization",
    },
    {
        "id": "adam-optimizer",
        "title": "Adam: A Method for Stochastic Optimization",
        "authors": "Kingma & Ba",
        "year": 2014,
        "arxiv_url": "https://arxiv.org/abs/1412.6980",
        "category": "Foundations",
        "description": "Combines momentum and adaptive learning rates for efficient optimization.",
        "suggested_repo_name": "adam-optimizer-impl",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # COMPUTER VISION
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "vit",
        "title": "An Image is Worth 16x16 Words: Transformers for Image Recognition",
        "authors": "Dosovitskiy et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2010.11929",
        "category": "Computer Vision",
        "description": "Applies Transformer architecture directly to image patches for classification.",
        "suggested_repo_name": "vision-transformer",
    },
    {
        "id": "yolov1",
        "title": "You Only Look Once: Unified, Real-Time Object Detection",
        "authors": "Redmon et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1506.02640",
        "category": "Computer Vision",
        "description": "Frames object detection as a single regression problem from image pixels to bounding boxes.",
        "suggested_repo_name": "yolo-object-detection",
    },
    {
        "id": "unet",
        "title": "U-Net: Convolutional Networks for Biomedical Image Segmentation",
        "authors": "Ronneberger et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1505.04597",
        "category": "Computer Vision",
        "description": "Encoder-decoder with skip connections for precise biomedical image segmentation.",
        "suggested_repo_name": "unet-segmentation",
    },
    {
        "id": "faster-rcnn",
        "title": "Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks",
        "authors": "Ren et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1506.01497",
        "category": "Computer Vision",
        "description": "Introduces Region Proposal Networks for efficient two-stage object detection.",
        "suggested_repo_name": "faster-rcnn-impl",
    },
    {
        "id": "alexnet",
        "title": "ImageNet Classification with Deep Convolutional Neural Networks",
        "authors": "Krizhevsky et al.",
        "year": 2012,
        "arxiv_url": "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html",
        "category": "Computer Vision",
        "description": "Deep CNN that sparked the deep learning revolution by winning ImageNet 2012.",
        "suggested_repo_name": "alexnet-imagenet",
    },
    {
        "id": "swin-transformer",
        "title": "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows",
        "authors": "Liu et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2103.14030",
        "category": "Computer Vision",
        "description": "Hierarchical Transformer with shifted windows for efficient multi-scale vision tasks.",
        "suggested_repo_name": "swin-transformer",
    },
    {
        "id": "detr",
        "title": "End-to-End Object Detection with Transformers (DETR)",
        "authors": "Carion et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2005.12872",
        "category": "Computer Vision",
        "description": "Treats object detection as a set prediction problem using Transformers and bipartite matching.",
        "suggested_repo_name": "detr-detection",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # NLP
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "word2vec",
        "title": "Efficient Estimation of Word Representations in Vector Space",
        "authors": "Mikolov et al.",
        "year": 2013,
        "arxiv_url": "https://arxiv.org/abs/1301.3781",
        "category": "NLP",
        "description": "Learns dense word embeddings using Skip-gram and CBOW architectures.",
        "suggested_repo_name": "word2vec-implementation",
    },
    {
        "id": "seq2seq",
        "title": "Sequence to Sequence Learning with Neural Networks",
        "authors": "Sutskever et al.",
        "year": 2014,
        "arxiv_url": "https://arxiv.org/abs/1409.3215",
        "category": "NLP",
        "description": "Encoder-decoder LSTM architecture for machine translation.",
        "suggested_repo_name": "seq2seq-translation",
    },
    {
        "id": "t5",
        "title": "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer",
        "authors": "Raffel et al.",
        "year": 2019,
        "arxiv_url": "https://arxiv.org/abs/1910.10683",
        "category": "NLP",
        "description": "Treats every NLP task as a text-to-text problem using a unified Transformer model.",
        "suggested_repo_name": "t5-text-to-text",
    },
    {
        "id": "llama",
        "title": "LLaMA: Open and Efficient Foundation Language Models",
        "authors": "Touvron et al.",
        "year": 2023,
        "arxiv_url": "https://arxiv.org/abs/2302.13971",
        "category": "NLP",
        "description": "Efficient open-source LLMs competitive with much larger proprietary models.",
        "suggested_repo_name": "llama-implementation",
    },
    {
        "id": "elmo",
        "title": "Deep Contextualized Word Representations (ELMo)",
        "authors": "Peters et al.",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1802.05365",
        "category": "NLP",
        "description": "Context-dependent word embeddings from bidirectional LSTM language models.",
        "suggested_repo_name": "elmo-embeddings",
    },
    {
        "id": "glove",
        "title": "GloVe: Global Vectors for Word Representation",
        "authors": "Pennington et al.",
        "year": 2014,
        "arxiv_url": "https://nlp.stanford.edu/pubs/glove.pdf",
        "category": "NLP",
        "description": "Word embeddings from global co-occurrence statistics with log-bilinear model.",
        "suggested_repo_name": "glove-embeddings",
    },
    {
        "id": "rag",
        "title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "authors": "Lewis et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2005.11401",
        "category": "NLP",
        "description": "Combines retrieval with generation to ground LLM outputs in external knowledge.",
        "suggested_repo_name": "rag-implementation",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # GENERATIVE MODELS
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "gan",
        "title": "Generative Adversarial Networks",
        "authors": "Goodfellow et al.",
        "year": 2014,
        "arxiv_url": "https://arxiv.org/abs/1406.2661",
        "category": "Generative Models",
        "description": "Two-player game between generator and discriminator networks for data generation.",
        "suggested_repo_name": "gan-from-scratch",
    },
    {
        "id": "vae",
        "title": "Auto-Encoding Variational Bayes",
        "authors": "Kingma & Welling",
        "year": 2013,
        "arxiv_url": "https://arxiv.org/abs/1312.6114",
        "category": "Generative Models",
        "description": "Variational inference framework for learning latent representations.",
        "suggested_repo_name": "vae-implementation",
    },
    {
        "id": "ddpm",
        "title": "Denoising Diffusion Probabilistic Models",
        "authors": "Ho et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2006.11239",
        "category": "Generative Models",
        "description": "Generates images by learning to reverse a gradual noising process.",
        "suggested_repo_name": "ddpm-diffusion",
    },
    {
        "id": "stylegan",
        "title": "A Style-Based Generator Architecture for Generative Adversarial Networks",
        "authors": "Karras et al.",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1812.04948",
        "category": "Generative Models",
        "description": "Style-based generator allowing fine-grained control over image synthesis.",
        "suggested_repo_name": "stylegan-impl",
    },
    {
        "id": "flow-matching",
        "title": "Flow Matching for Generative Modeling",
        "authors": "Lipman et al.",
        "year": 2022,
        "arxiv_url": "https://arxiv.org/abs/2210.02747",
        "category": "Generative Models",
        "description": "Simpler alternative to diffusion models using continuous normalizing flows.",
        "suggested_repo_name": "flow-matching-gen",
    },
    {
        "id": "neural-style-transfer",
        "title": "A Neural Algorithm of Artistic Style",
        "authors": "Gatys et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1508.06576",
        "category": "Generative Models",
        "description": "Transfers artistic styles between images using CNN feature representations.",
        "suggested_repo_name": "neural-style-transfer",
    },
    {
        "id": "pix2pix",
        "title": "Image-to-Image Translation with Conditional Adversarial Networks",
        "authors": "Isola et al.",
        "year": 2016,
        "arxiv_url": "https://arxiv.org/abs/1611.07004",
        "category": "Generative Models",
        "description": "Conditional GAN for paired image-to-image translation tasks.",
        "suggested_repo_name": "pix2pix-translation",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # REINFORCEMENT LEARNING
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "dqn",
        "title": "Playing Atari with Deep Reinforcement Learning",
        "authors": "Mnih et al.",
        "year": 2013,
        "arxiv_url": "https://arxiv.org/abs/1312.5602",
        "category": "Reinforcement Learning",
        "description": "Deep Q-Network learns to play Atari games from raw pixels.",
        "suggested_repo_name": "dqn-atari",
    },
    {
        "id": "ppo",
        "title": "Proximal Policy Optimization Algorithms",
        "authors": "Schulman et al.",
        "year": 2017,
        "arxiv_url": "https://arxiv.org/abs/1707.06347",
        "category": "Reinforcement Learning",
        "description": "Stable policy gradient method with clipped surrogate objective.",
        "suggested_repo_name": "ppo-implementation",
    },
    {
        "id": "alphago",
        "title": "Mastering the Game of Go with Deep Neural Networks and Tree Search",
        "authors": "Silver et al.",
        "year": 2016,
        "arxiv_url": "https://www.nature.com/articles/nature16961",
        "category": "Reinforcement Learning",
        "description": "Combines deep learning with Monte Carlo tree search to master Go.",
        "suggested_repo_name": "alphago-mcts",
    },
    {
        "id": "a3c",
        "title": "Asynchronous Methods for Deep Reinforcement Learning",
        "authors": "Mnih et al.",
        "year": 2016,
        "arxiv_url": "https://arxiv.org/abs/1602.01783",
        "category": "Reinforcement Learning",
        "description": "Parallel actor-critic agents for faster and more stable RL training.",
        "suggested_repo_name": "a3c-implementation",
    },
    {
        "id": "sac",
        "title": "Soft Actor-Critic: Off-Policy Maximum Entropy Deep RL",
        "authors": "Haarnoja et al.",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1801.01290",
        "category": "Reinforcement Learning",
        "description": "Maximum entropy RL for robust and sample-efficient continuous control.",
        "suggested_repo_name": "soft-actor-critic",
    },
    {
        "id": "dreamer",
        "title": "Dream to Control: Learning Behaviors by Latent Imagination",
        "authors": "Hafner et al.",
        "year": 2019,
        "arxiv_url": "https://arxiv.org/abs/1912.01603",
        "category": "Reinforcement Learning",
        "description": "World model that learns behaviors by imagining trajectories in latent space.",
        "suggested_repo_name": "dreamer-world-model",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # GRAPH NEURAL NETWORKS
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "gcn",
        "title": "Semi-Supervised Classification with Graph Convolutional Networks",
        "authors": "Kipf & Welling",
        "year": 2016,
        "arxiv_url": "https://arxiv.org/abs/1609.02907",
        "category": "Graph Neural Networks",
        "description": "Spectral graph convolutions for node classification on graph-structured data.",
        "suggested_repo_name": "gcn-node-classification",
    },
    {
        "id": "gat",
        "title": "Graph Attention Networks",
        "authors": "Veličković et al.",
        "year": 2017,
        "arxiv_url": "https://arxiv.org/abs/1710.10903",
        "category": "Graph Neural Networks",
        "description": "Attention mechanism over graph neighborhoods for weighted aggregation.",
        "suggested_repo_name": "graph-attention-network",
    },
    {
        "id": "graphsage",
        "title": "Inductive Representation Learning on Large Graphs",
        "authors": "Hamilton et al.",
        "year": 2017,
        "arxiv_url": "https://arxiv.org/abs/1706.02216",
        "category": "Graph Neural Networks",
        "description": "Samples and aggregates features from node neighborhoods for inductive learning.",
        "suggested_repo_name": "graphsage-impl",
    },
    {
        "id": "gin",
        "title": "How Powerful are Graph Neural Networks?",
        "authors": "Xu et al.",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1810.00826",
        "category": "Graph Neural Networks",
        "description": "Analyzes GNN expressiveness and proposes Graph Isomorphism Network.",
        "suggested_repo_name": "gin-graph-network",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # OPTIMIZATION & TRAINING
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "knowledge-distillation",
        "title": "Distilling the Knowledge in a Neural Network",
        "authors": "Hinton et al.",
        "year": 2015,
        "arxiv_url": "https://arxiv.org/abs/1503.02531",
        "category": "Optimization & Training",
        "description": "Trains a small student network to mimic a large teacher using soft targets.",
        "suggested_repo_name": "knowledge-distillation",
    },
    {
        "id": "mixup",
        "title": "mixup: Beyond Empirical Risk Minimization",
        "authors": "Zhang et al.",
        "year": 2017,
        "arxiv_url": "https://arxiv.org/abs/1710.09412",
        "category": "Optimization & Training",
        "description": "Data augmentation by training on convex combinations of training examples.",
        "suggested_repo_name": "mixup-training",
    },
    {
        "id": "lottery-ticket",
        "title": "The Lottery Ticket Hypothesis",
        "authors": "Frankle & Carlin",
        "year": 2018,
        "arxiv_url": "https://arxiv.org/abs/1803.03635",
        "category": "Optimization & Training",
        "description": "Dense networks contain sparse subnetworks that can train to full accuracy.",
        "suggested_repo_name": "lottery-ticket-hypothesis",
    },
    {
        "id": "lora",
        "title": "LoRA: Low-Rank Adaptation of Large Language Models",
        "authors": "Hu et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2106.09685",
        "category": "Optimization & Training",
        "description": "Parameter-efficient fine-tuning by injecting low-rank weight updates.",
        "suggested_repo_name": "lora-finetuning",
    },
    {
        "id": "contrastive-learning",
        "title": "A Simple Framework for Contrastive Learning (SimCLR)",
        "authors": "Chen et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2002.05709",
        "category": "Optimization & Training",
        "description": "Self-supervised visual representation learning via contrastive loss on augmentations.",
        "suggested_repo_name": "simclr-contrastive",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # MULTIMODAL & MISC
    # ═══════════════════════════════════════════════════════════════════════
    {
        "id": "clip",
        "title": "Learning Transferable Visual Models From Natural Language Supervision",
        "authors": "Radford et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2103.00020",
        "category": "Multimodal",
        "description": "Contrastive pre-training to align image and text embeddings for zero-shot transfer.",
        "suggested_repo_name": "clip-implementation",
    },
    {
        "id": "dalle",
        "title": "Zero-Shot Text-to-Image Generation (DALL·E)",
        "authors": "Ramesh et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2102.12092",
        "category": "Multimodal",
        "description": "Generates images from text descriptions using a Transformer trained on text-image pairs.",
        "suggested_repo_name": "dalle-text-to-image",
    },
    {
        "id": "whisper",
        "title": "Robust Speech Recognition via Large-Scale Weak Supervision",
        "authors": "Radford et al.",
        "year": 2022,
        "arxiv_url": "https://arxiv.org/abs/2212.04356",
        "category": "Multimodal",
        "description": "Large-scale speech recognition model trained on diverse audio data.",
        "suggested_repo_name": "whisper-asr",
    },
    {
        "id": "nerf",
        "title": "NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis",
        "authors": "Mildenhall et al.",
        "year": 2020,
        "arxiv_url": "https://arxiv.org/abs/2003.08934",
        "category": "Multimodal",
        "description": "Learns 3D scene representations from 2D images using neural radiance fields.",
        "suggested_repo_name": "nerf-view-synthesis",
    },
    {
        "id": "flamingo",
        "title": "Flamingo: a Visual Language Model for Few-Shot Learning",
        "authors": "Alayrac et al.",
        "year": 2022,
        "arxiv_url": "https://arxiv.org/abs/2204.14198",
        "category": "Multimodal",
        "description": "Visual language model that handles interleaved text and image inputs for few-shot tasks.",
        "suggested_repo_name": "flamingo-vlm",
    },
    {
        "id": "mae",
        "title": "Masked Autoencoders Are Scalable Vision Learners",
        "authors": "He et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2111.06377",
        "category": "Multimodal",
        "description": "Self-supervised vision learning by masking image patches and reconstructing them.",
        "suggested_repo_name": "mae-vision-learner",
    },
    {
        "id": "stable-diffusion",
        "title": "High-Resolution Image Synthesis with Latent Diffusion Models",
        "authors": "Rombach et al.",
        "year": 2021,
        "arxiv_url": "https://arxiv.org/abs/2112.10752",
        "category": "Generative Models",
        "description": "Diffusion models in latent space for efficient high-resolution image generation.",
        "suggested_repo_name": "latent-diffusion",
    },
]


# ── Category list (computed) ─────────────────────────────────────────────────

CATEGORIES = sorted(set(p["category"] for p in PAPERS))


def get_catalog() -> List[Dict]:
    """Return the full paper catalog."""
    return PAPERS


def get_categories() -> List[str]:
    """Return sorted list of unique categories."""
    return CATEGORIES
